name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MLIR_SYS_180_PREFIX: /usr/lib/llvm-18/
      LLVM_SYS_180_PREFIX: /usr/lib/llvm-18/
      TABLEGEN_180_PREFIX: /usr/lib/llvm-18/
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.78.0
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    - name: add llvm deb repository
      uses: myci-actions/add-deb-repo@10
      with:
            repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main
            repo-name: llvm-repo
            keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
    - name: Install LLVM
      run: sudo apt-get install llvm-18 llvm-18-dev llvm-18-runtime libpolly-18-dev
    - run: cargo test
  test-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo clippy -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
